src/account/urls.py
from django.conf.urls import url

from .views import (RegisterView, 
				   LoginView, 
				   AccountHomeView,
				   AccountEmailActivateView,
				   check_your_email,
				   )

# url(r'^$',views.IndexView.as_view(), name='index'),


app_name = 'account'
urlpatterns = [
		#url(r'^login/$', login_page, name="login"),
		#url(r'^register/$', register_page, name="register"),



		url(r'^login/$', LoginView.as_view(), name="login"),
		url(r'^register/$', RegisterView.as_view(), name="register"),
		url(r'^home/$', AccountHomeView.as_view(), name="home"),
		url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', AccountEmailActivateView.as_view(), name="email-activate"),
		url(r'^email/resend-activation/$', AccountEmailActivateView.as_view(), name="resend-activation"),
		url(r'^check-your-email/$',check_your_email, name='check-your-email'),

]

src/carts/urls.py
from django.conf.urls import url

from .views import payment_plans_view, cart_update, confirm_purchase_view, payment_cancel_view, payment_success_view
# url(r'^$',views.IndexView.as_view(), name='index'),


app_name = 'carts'
urlpatterns = [
		url(r'^payment-plans/$', payment_plans_view, name="payment-plan"),
		url(r'^update-cart/$', cart_update, name="update"),
		url(r'^confirm-purchase/$', confirm_purchase_view, name="confirm_purchase_view"),
		url(r'^payment-success/(?P<paid_using>[\w-]+)/cancel/$', payment_cancel_view, name="cancel"),
		url(r'^payment-success/(?P<paid_using>[\w-]+)/$', payment_success_view, name="success"),

		

		#https://www.engineeringstudentplaybook.com/carts/payment-success/paypal

		#http://127.0.0.1:8000/carts/payment-success/paypal/cancel
		#https://www.engineeringstudentplaybook.com/carts/payment-success/paypal/cancel


	
]

src/pages/templates/pages/about_page.html
{% extends 'base.html' %}

{% block content %}
<div class='container'>

<div class='row alert alert-secondary mt-3'>
	<div class='col'>
		<blockquote class="blockquote text-center mt-3">
		  <p class="mb-0">{{ quote.quote }}</p>
		  <footer class="blockquote-footer">{{ quote.author }},<cite title="Source Title"> {{ quote.source }}</cite></footer>
		</blockquote>	
	</div>
</div>



<div class='row justify-text-center mb-5 alert button-colour dark-purple-text'>
	<div class='col text-center'>

			<p><h5>{{ about_page_assets.content1 }}</h5></p>

			<p><h5>{{ about_page_assets.content2 }}</h5></p>

			<p><h5>{{ about_page_assets.content3 }}</h5></p>

			<p><h5>{{ about_page_assets.content4 }}</h5></p>


		</p>

	</div>
</div>











</div>
{% endblock %}

src/pages/templates/pages/connect_page.html
{% extends 'base.html' %}

{% block content %}
<div class='container'>

	<div class='row mt-3 mx-auto justify-content-center alert '>

		<div class='col mx-auto text-center'>
			<h3>Connect </h3>
			<p>engplaybook@gmail.com</p>
		</div>


	</div>








</div>
{% endblock %}

src/pages/templates/pages/contact_page.html
{% extends 'base.html' %}

{% block content %}
<div class='container'>

	<div class='row mt-3 mx-auto justify-content-center alert '>

		<div class='col mx-auto text-center'>
			<h3>Contact Us</h3>
			<p>engplaybook@gmail.com</p>
		</div>


	</div>






<!-- <h1>{{title}}</h1>
 

<p>{{content}}</p>
 -->



</div>
{% endblock %}

src/pages/templates/pages/home_page.html
{% extends 'base.html' %}


{% block content %}
{% url 'account:register' as register %}
{% url 'carts:payment-plan' as payment_plans_url %}



<div class='container-fluid'>
	
  <meta name="description" content="Learn about CVs, Cover Letters, Excel, Maths and more.">


	{% if request.user.is_authenticated and request.user.full_access %}
		<blockquote class="blockquote text-center mt-3 alert alert-secondary">
		  <p class="mb-0">{{ quote.quote }}</p>
		  <footer class="blockquote-footer">{{ quote.author }},<cite title="Source Title"> {{ quote.source }}</cite></footer>
		</blockquote>
	{% else %}

		{% if request.user.is_authenticated and not request.user.full_access %}
			<a href='{{ payment_plans_url }}'>
				<div class='col-12 mt-3 text-center alert alert-warning'>
		 			<h4 class='mt-2'>{{ home_page_assets.content2 }}</h4>
			 	</div>
			</a>
		{% else %}
				<!-- button-colour white-text -->
			<a href='{{ register }}'>
				<div class='col-12 mt-3 text-center alert alert-info'>
			 		<h4 class='mt-2'>{{ home_page_assets.content1 }}</h4>
			 		<h3 class='mt-2'><b>{{ home_page_assets.content3 }}</b></h3>
				</div>

				

			</a>
		{% endif %}	
			 

	{% endif %}

</div>


<div class='container'>





<h3 class='mt-3'>Featured Tutorials</h3>
<hr>

<br>



<div class='row'>

	{% for obj in featured_tutorials_qs %}






			<div class='col mt-3'>



			{% include 'pages/snippets/card.html' with instance=obj %}

			

		{% if forloop.counter|divisibleby:3 %}
			</div> </div><div class='row'><div class='col-12'><hr/></div>
		{% elif forloop.counter|divisibleby:3 %}
			</div> </div><div class='row'><div class='col-12'><hr/></div>
		{% else %}
			</div>
		{% endif %}

		
	{% endfor %}



	

	

		
	
	



</div>


<br>
<br>


{% if not request.user.is_authenticated or request.user.is_authenticated and not request.user.full_access %}
	{% include 'carts/snippets/compare-plans.html' with button=False price=product.price %}
	<br>
{% endif %}
















<br>
<br>
<br>
<br>
<br>











</div>
{% endblock %}

src/pages/templates/pages/pricing_page.html
{% extends 'base.html' %}





{% block content %}

{% url 'account:register' as register %}
{% url 'carts:payment-plan' as payment_plans_url %}



<div class='container'>


	<h2 class='mt-3'>Pricing</h2>
	<hr>


	{% if request.user.is_authenticated and request.user.full_access %}
		<blockquote class="blockquote text-center mt-3 alert alert-secondary">
		  <p class="mb-0">{{ quote.quote }}</p>
		  <footer class="blockquote-footer">{{ quote.author }},<cite title="Source Title"> {{ quote.source }}</cite></footer>
		</blockquote>
	{% else %}

		{% if request.user.is_authenticated and not request.user.full_access %}
			<a href='{{ payment_plans_url }}'>
				<div class='col-12 mt-3 text-center alert alert-warning'>
		 			<h4 class='mt-2'>{{ home_page_assets.content2 }}</h4>
			 	</div>
			</a>
		{% else %}
				<!-- button-colour white-text -->
			<a href='{{ register }}'>
				<div class='col-12 mt-3 text-center alert alert-info'>
			 		<h4 class='mt-2'>{{ home_page_assets.content1 }}</h4>
				</div>
			</a>
		{% endif %}	
			 

	{% endif %}



	{% include 'carts/snippets/compare-plans.html' with button=False price=product.price %}



</div>
{% endblock %}

src/pages/templates/pages/privacy_policy_page.html
{% extends 'base.html' %}

{% block content %}
<div class='container'>

	<div class='row mt-3 '>

		<div class='col '>

			<h2 class='mt-3'>Privacy Policy</h2>
			<hr>


				{% autoescape off %}
					<p>{{ asset.content1 }}</p>
				{% endautoescape %}



		</div>


	</div>








</div>
{% endblock %}

src/pages/templates/pages/sub_category_list_view.html
{% extends 'base.html' %}


{% block content %}
<div class="container">


<h2 class='mt-3'>Sub Categories</h2>
<hr>


<div class='row'>
	{% for obj in object_list %}
		<div class='col mt-3'>

		<!-- {{ forloop.counter }} -->

			{% include 'pages/snippets/card.html' with instance=obj %}



			{% if forloop.counter|divisibleby:3 %}
				</div> </div><div class='row'><div class='col-12'><hr/></div>
			{% elif forloop.counter|divisibleby:3 %}
				</div> </div><div class='row'><div class='col-12'><hr/></div>

			{% else %}

		</div>
			{% endif %}


		
	{% endfor %}
</div>



</div>
{% endblock %}

src/pages/templates/pages/tutorial_view.html
{% extends 'base.html' %}





{% block sidebar %}
{% endblock %}

	



{% block content %}
<div class='container-fluid'>

{% if request.user.is_authenticated and request.user.full_access or object.is_free %}



	<div class='row'>

		<div class='order-1 order-md-1 col-12 col-md-2 border-right py-3 bg-sidebar-light '>
			<div class='d-sm-none d-md-block d-none d-sm-block'> <!-- To disapear when the screeen gets smaller -->
			
				<!-- <h3>Contents</h3> -->
				<div class="list-group">

					

					<a href="{{ sub_category.get_absolute_url }}" class="list-group-item list-group-item-action">Back</a>

				{% for sidebar_obj in sidebar_qs%}

						{% if sidebar_obj == object %}

							<a href="{{ sidebar_obj.get_absolute_url }}" class="list-group-item list-group-item-action dark-purple white-text">{{sidebar_obj.title}}</a>

						{% else %}

							<a href="{{ sidebar_obj.get_absolute_url }}" class="list-group-item list-group-item-action ">{{sidebar_obj.title}}</a>

						{% endif %}

				{% endfor %}

			
				</div>
			</div>
		</div>




		

		<div class='order-2 order-md-2 col-12 col-md-10 min-height min-page-height py-3'>

			<h2>{{ object.title }}</h2>
			<hr>

			<!-- Video -->
			<!-- <div class="embed-responsive embed-responsive-16by9">
				<p><iframe class="embed-responsive-item" src="{{ object.video_link }}"></iframe></p>
			</div>

			<br>
		
			<p>{{ object.content }}</p>


			<p>{{ object.text1 }}</p>
			

			{% if image1 %}
			<div class='d-flex justify-content-center'>
				<p><img class="img-fluid" src="{{ object.image1.url }}" alt="Responsive image"></p>
			</div>
			{% endif %}
			

			<p>{{ object.text2}}</p>

			{% if image3 %}
			<div class='d-flex justify-content-center'>
				<p><img class="img-fluid" src="{{ object.image2.url }}" alt="Responsive image"></p>
			</div>
			{% endif %}
			



			<p>{{ object.text3 }}</p>

			{% if image3 %}
			<div class='d-flex justify-content-center'>
				<p><img class="img-fluid" src="{{ object.image3.url }}" alt="Responsive image"></p>
			</div>
			{% endif %}



			<p>{{ object.text4 }}</p>

			{% if image4 %}
			<div class='d-flex justify-content-center'>
				<p><img class="img-fluid" src="{{ object.image4.url }}" alt="Responsive image"></p>
			</div>
			{% endif %} -->

			

			{% for content in object.get_content %}
			<div class='row'>

				{% if content.video_link %}
				<!-- <div class='col-12 col-md-10 mx-auto'>	 -->
				<div class='{{ content.video_link_col_params }}'>					
						<div class="embed-responsive embed-responsive-16by9">
						<p><iframe class="embed-responsive-item" src="{{ content.video_link }}"></iframe></p>
						</div>
						<br>
						<!-- {% autoescape off %}
							{{ content.video_link }}
						{% endautoescape %} -->
				</div>
				{% endif %}


				{% if content.image %}
				<!-- <div class='col-12 col-md-5 mx-auto'> -->
				<div class='{{ content.image_col_params }}'>	
						<div class='d-flex justify-content-center'>
							<p><img class="img-fluid" src="{{ content.image.url }}" alt="Responsive image"></p>
						</div>
				</div>
				{% endif %}


				{% if content.text %}
				<!-- <div class='col-12 mx-auto'> -->
				<div class='{{ content.text_col_params }}'>
						<p>{{ content.text }}</p>
				</div>
				{% endif %}


				{% if content.html_text %}
				<!-- <div class='col-12 mx-auto'> -->
				<div class='{{ content.html_text_col_params }}'>
					{% autoescape off %}
						<p>{{ content.html_text }}</p>
					{% endautoescape %}
				</div>
				{% endif %}

				

			</div>


			<br>
			{% endfor %}

			







			<br>
			<br>



			{% if object.get_downloads %}

				<h3>Downloadable Resources</h3>
				<hr>

				{% for download in object.get_downloads %}
					<a href='{{ download.get_download_url }}'><p>{{ download.display_name }}</p></a>
				{% endfor %}

			{% endif %}





			






	



		</div>


	</div>







{% else %}

	<!-- <meta http-equiv="REFRESH" content="0;url={% url 'account:login' %}"> -->



	<div class='row mt-5 mb-5 justify-content-center'>
		<h1>This tutorial is only available to premium members.</h1>
	</div>

	<div class='row mt-5 mb-5	 justify-content-center'>
		<a href="{% url 'account:register' %}" class=" btn btn-danger">Get Premium Membership</a>
	</div>


{% endif %}




</div>
{% endblock %}

src/pages/templates/pages/tutorials_list_view.html
{% extends 'base.html' %}


{% block content %}
<div class='container'>

<h2 class='mt-3'>Tutorials</h2>
<hr>


<div class='row '>
	{% for obj in object_list %}
		


<div class='col mt-3 '>

		<!-- {{ forloop.counter }} -->

			{% include 'pages/snippets/card.html' with instance=obj %}


			{% if forloop.counter|divisibleby:3 %}

				</div> </div><div class='row '><div class='col-12'><hr/></div>

			{% elif forloop.counter|divisibleby:3 %}
				
				</div> </div><div class='row  '><div class='col-12'><hr/></div>

			{% else %}

		</div>


			{% endif %}





		
	{% endfor %}
</div>



</div>
{% endblock %}