src/account/urls.py
from django.conf.urls import url

from .views import (RegisterView, 
				   LoginView, 
				   AccountHomeView,
				   AccountEmailActivateView,
				   check_your_email,
				   )

# url(r'^$',views.IndexView.as_view(), name='index'),


app_name = 'account'
urlpatterns = [
		#url(r'^login/$', login_page, name="login"),
		#url(r'^register/$', register_page, name="register"),



		url(r'^login/$', LoginView.as_view(), name="login"),
		url(r'^register/$', RegisterView.as_view(), name="register"),
		url(r'^home/$', AccountHomeView.as_view(), name="home"),
		url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', AccountEmailActivateView.as_view(), name="email-activate"),
		url(r'^email/resend-activation/$', AccountEmailActivateView.as_view(), name="resend-activation"),
		url(r'^check-your-email/$',check_your_email, name='check-your-email'),

]

src/carts/urls.py
from django.conf.urls import url

from .views import payment_plans_view, cart_update, confirm_purchase_view, payment_cancel_view, payment_success_view
# url(r'^$',views.IndexView.as_view(), name='index'),


app_name = 'carts'
urlpatterns = [
		url(r'^payment-plans/$', payment_plans_view, name="payment-plan"),
		url(r'^update-cart/$', cart_update, name="update"),
		url(r'^confirm-purchase/$', confirm_purchase_view, name="confirm_purchase_view"),
		url(r'^payment-success/(?P<paid_using>[\w-]+)/cancel/$', payment_cancel_view, name="cancel"),
		url(r'^payment-success/(?P<paid_using>[\w-]+)/$', payment_success_view, name="success"),

		

		#https://www.engineeringstudentplaybook.com/carts/payment-success/paypal

		#http://127.0.0.1:8000/carts/payment-success/paypal/cancel
		#https://www.engineeringstudentplaybook.com/carts/payment-success/paypal/cancel


	
]

src/engplaybook/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LogoutView



urlpatterns = [
    url(r'^search/', include('search.urls', namespace='search')),
	url(r'^', include('pages.urls', namespace='pages')),
	url(r'^account/', include('account.urls', namespace='account')),
    url(r'^account/config/', include('account.passwords.urls')),
    url(r'^billing/', include('billing.urls', namespace='billing')),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base/css.html
{% load static %}

<!-- Bootstrap CSS -->
<link 
rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


<!-- Font awesome CSS -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

<!-- jquery confirm -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">



<!-- Custom stripe styling -->
<link rel="stylesheet" href="{% static 'css/stripe-custom-style.css' %}">

src/templates/base/footer.html
{% url 'pages:contact' as contact_page_url %}
{% url 'pages:about' as about_page_url %}
{% url 'pages:connect' as connect_page_url %}


<div class='container-fluid mt-3 mb-2'>



	<div class='row justify-text-center mb-2'>
		<div class='col text-center'>
			<a href='{{ about_page_url }}'>About</a>
			·
			<a href='{{ contact_page_url }}'>Contact</a>
			·
			<a href='{{ connect_page_url}}'>Connect</a>
			·
			<a href="{% url 'pages:privacy_policy' %}">Privacy Policy</a>

		</div>
	</div>


	<div class='row justify-text-center'>
		<div class='col text-center  '>
			© Copyright · engplaybook.com
		</div>
	</div>

</div>

src/templates/base/js.html
{% load static %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
</script>



<!-- stripe js -->
<script src="https://js.stripe.com/v3/"></script>



<!-- jquery confirm -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>


<!-- js render -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/0.9.90/jsrender.min.js"></script>
{% include 'base/js_templates.html' %}

<!--django secure ajax -->
<script src='{% static "js/csrf.ajax.js" %}'></script>

<!-- Need to fix - old ecommerce project -->
<!-- ecommerce custom js -->
<script src='{% static "js/ecommerce.js" %}'></script>


<!-- engplaybook main js -->
<script src='{% static "js/engplaybook.main.js" %}'></script>

src/templates/base/js_templates.html
{% verbatim %}
<!-- stripe template form -->
<script id="stripeTemplate" type="text/x-jsrender">
    <form class='payment-form' action="" method="post" id="payment-form" data-token='{{:publishKey}}' data-next-url='{{:nextUrl}}'>
  <div class="form-row">
    <!-- <label for="card-element">
      Credit or debit card
    </label> -->
    <div id="card-element" class='form-control'> 
      <!-- a Stripe Element will be inserted here. -->
    </div>
    <!-- Used to display form errors -->
    <div id="card-errors" role="alert"></div>
  </div>
  <button class='btn  my-3 btn-load btn-block' style='background-color: #34314f; color: #FFFFFF '>{{:btnTitle }}</button>
    </form>
</script>
{% endverbatim %}

src/templates/base/navbar.html
{% url 'pages:home' as home_page_url %}
{% url 'pages:about' as about_page_url %}
{% url 'pages:contact' as contact_page_url %}
{% url 'pages:pricing' as pricing_page_url %}




{% url 'account:login' as login %}
{% url 'account:register' as register %}
{% url 'account:home' as account_home_url %}



{% url 'logout' as logout %}




<!-- navbar navbar-expand-lg navbar-light bg-light -->

<!-- style='background-color: #181238' -->


<nav class="navbar navbar-expand-lg navbar-dark nav-bar-color "     >
  <!-- <a class="navbar-brand" href="#">
    <img src="#" width="30" height="30" class="d-inline-block align-top" alt="">
    Bootstrap
  </a> -->
  <a class="navbar-brand blue-color" href="{{home_page_url}}"><b>{% if brand_name %}{{brand_name}}{% endif %}</b></a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ">


      <li class="nav-item dropdown mr-3 ">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Topics
        </a>


        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          {% for category in categories_qs %}
            <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.title }}</a>
          {% endfor %}

           <!-- <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a> -->
        </div>
      </li>



            
            


     
        {% include 'search/snippets/search-form.html' %}
      
            


      </ul>






      <ul class="navbar-nav ml-auto mr-3">


     <!--  <li class="nav-item {% if request.path == home_page_url %}active{% endif %}">
        <a class="nav-link" href="{{home_page_url}}">Home <span class="sr-only">(current)</span></a>
      </li> -->

      

      <li class="nav-item {% if request.path == pricing_page_url %}active{% endif %}">
        <a class="nav-link "  href="{{pricing_page_url}}">Pricing</a>
      </li>

      <li class="nav-item {% if request.path == about_page_url %}active{% endif %}">
        <a class="nav-link "  href="{{about_page_url}}">About</a>
      </li>

      <li class="nav-item {% if request.path == contact_page_url %}active{% endif %}">
        <a class="nav-link" href="{{contact_page_url}}">Contact</a>
      </li>


      
      
   
    
    

       {% if request.user.is_authenticated %}
         <!-- <li class="nav-item {% if request.path == login %}active{% endif %} ml-auto">
          <a class="nav-link" href="{{ logout }}">Logout</a>
        </li> -->

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ account_home_url }}">Home</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ logout }}">Logout</a>
          </div>
        </li>

      {% else %}
         <li class="nav-item {% if request.path == register %}active{% endif %}">
          <a class="nav-link" href="{{ register }}">Register</a>
         </li>
        <li class="nav-item {% if request.path == login %}active{% endif %}">
          <a class="nav-link" href="{{ login }}">Login</a>
        </li>
      {% endif %}


    </ul>

    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->

    


    

    

  </div>
</nav>