src/carts/urls.py
from django.conf.urls import url

from .views import payment_plans_view, cart_update, confirm_purchase_view, payment_cancel_view, payment_success_view
# url(r'^$',views.IndexView.as_view(), name='index'),


app_name = 'carts'
urlpatterns = [
		url(r'^payment-plans/$', payment_plans_view, name="payment-plan"),
		url(r'^update-cart/$', cart_update, name="update"),
		url(r'^confirm-purchase/$', confirm_purchase_view, name="confirm_purchase_view"),
		url(r'^payment-success/(?P<paid_using>[\w-]+)/cancel/$', payment_cancel_view, name="cancel"),
		url(r'^payment-success/(?P<paid_using>[\w-]+)/$', payment_success_view, name="success"),

		

		#https://www.engineeringstudentplaybook.com/carts/payment-success/paypal

		#http://127.0.0.1:8000/carts/payment-success/paypal/cancel
		#https://www.engineeringstudentplaybook.com/carts/payment-success/paypal/cancel


	
]

src/product/models.py
from django.db import models

# Create your models here.



class Product(models.Model):
	title 		= models.CharField(max_length=120)
	description	= models.TextField(null=True, blank=True)
	featured 	= models.BooleanField(default=False)
	active 		= models.BooleanField(default=True)
	price		= models.DecimalField(decimal_places=2, max_digits=20, default= 19.99) #the default price is just made-up
	updated     = models.DateTimeField(auto_now=True)
	timestamp   = models.DateTimeField(auto_now_add=True)
    


	def __str__(self):
		return self.title

src/product/views.py
from django.shortcuts import render

# Create your views here.

src/product/templates/product/snippets/update-cart.html
<!-- <form class='form-product-ajax' method='POST' action='{% url "carts:update" %}' data-endpoint='{% url "carts:update" %}' class="form"> {% csrf_token %}
    <input type='hidden' name='product_id' value='{{ product.id }}' />
    
    

    <span class='submit-span'>
        <button type='submit'  class='btn btn-success btn-block'>{{ product.description }}</button>
    </span>


</form> -->


{% load static %}
<!-- <link rel="stylesheet" type="text/css" href="{% static 'product/style.css' %}"> -->


<form class='' method='POST' action='{% url "carts:update" %}' data-endpoint='{% url "carts:update" %}' class="form"> {% csrf_token %}
    <input type='hidden' name='product_id' value='{{ product.id }}' />
    
    <!-- style='background-color: #34314f' -->
  
  <!-- style='background-color: #7bc6bc; color: #FFFFFF	' -->

    <span class='submit-span'>
        <button type='submit'  class=' btn btn-block button-colour white-text '  >{{ product.description }}</button>
    </span>


</form>